# Generated by Django 6.0.4 on 2026-04-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='base_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
