# Generated by Django 6.0.4 on 2026-06-05 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servicecategory_base_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo_proof',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_proofs/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='worker_docs/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_photos/'),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
